AWSTemplateFormatVersion: '2010-09-09'

Description: Internet Gateway e redes publica e privada

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway

    Properties:
      Tags:
        - Key: Name
          Value: G6-igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment

    Properties:
      VpcId:
        Fn::ImportValue: G6-VpcId

      InternetGatewayId:
        Ref: InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId:
        Fn::ImportValue: G6-VpcId

      CidrBlock: 10.0.0.0/26

      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region

      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: G6-sub-publica

  PublicRouteTable:
    Type: AWS::EC2::RouteTable

    Properties:
      VpcId:
        Fn::ImportValue: G6-VpcId

      Tags:
        - Key: Name
          Value: G6-rt-publica

  PublicDefaultRoute:
    Type: AWS::EC2::Route

    DependsOn:
      - InternetGatewayAttachment

    Properties:
      RouteTableId:
        Ref: PublicRouteTable

      DestinationCidrBlock: 0.0.0.0/0

      GatewayId:
        Ref: InternetGateway


  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation

    Properties:
      SubnetId:
        Ref: PublicSubnet

      RouteTableId:
        Ref: PublicRouteTable

  PrivateSubnet:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId:
        Fn::ImportValue: G6-VpcId

      CidrBlock: 10.0.0.64/26

      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region

      MapPublicIpOnLaunch: false

      Tags:
        - Key: Name
          Value: G6-sub-privada

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable

    Properties:
      VpcId:
        Fn::ImportValue: G6-VpcId

      Tags:
        - Key: Name
          Value: G6-rt-privada


  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation

    Properties:
      SubnetId:
        Ref: PrivateSubnet

      RouteTableId:
        Ref: PrivateRouteTable

Outputs:

  PublicSubnetId:
    Description: ID da subnet publica
    Value:
      Ref: PublicSubnet

    Export:
      Name: G6-PublicSubnetId


  PrivateSubnetId:
    Description: ID da subnet privada
    Value:
      Ref: PrivateSubnet

    Export:
      Name: G6-PrivateSubnetId